name: table-config-agent
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pytorch=2.3.0
  - pytorch-cuda=12.1
  - bitsandbytes
  - accelerate
  - transformers>=4.40
  - langchain
  - pydantic
  - huggingface_hub
  - ruamel.yaml
  - chromadb