name: table-config-agent-dev
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  # -- PROD -- #
  - python=3.11
  - pytorch=2.3.0
  - pytorch-cuda=12.1
  - bitsandbytes
  - accelerate
  - transformers>=4.40
  - langchain
  - pydantic
  - huggingface_hub
  - ruamel.yaml
  - chromadb
  - typer
  # -- DEV -- #
  - black
  - flake8
  - mypy
  - pytest
  # -- PROD.PIP -- #
  - pip
  - pip:
    - bmt