name: table-config-agent
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  # -- PROD -- #
  - python=3.11
  - pytorch=2.3.0
  - pytorch-cuda=12.1
  - accelerate
  - transformers>=4.40
  - langchain
  - langchain-community
  - pydantic
  - huggingface_hub
  - ruamel.yaml
  - chromadb
  - typer
  - numpy
  # -- PROD.PIP -- #
  - pip
  - pip:
    - bmt
    - -e .
    - bitsandbytes
variables:
  BNB_CUDA_VERSION: "121"